---
# vars file for create_n_deploy_instance

region: us-east-1
instance_type: t2.nano
ami: ami-759bc50a  # Ubuntu 16.04 LTS ami-759bc50a
project_name: testing
env: staging
app_code_user: "ubuntu" # remote user
hoststring: "ansible_ssh_user=ubuntu ansible_ssh_private_key_file=/home/sindhu/aws-private.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'"
hostpath: "hosts"
