#ansible-playbook -i hosts main.yml

- name: Create AWS instance
  hosts: 127.0.0.1
  connection: local
  gather_facts: False
  remote_user: ubuntu

  roles:
    - create_n_deploy_instance

- name: Create SSL certificates
  hosts: webserver
  become: yes
  become_method: sudo
  gather_facts: true
 
  roles:
    - create_n_deploy_ssl_certificate     

- name: Install nginx
  hosts: webserver
  become: yes
  become_method: sudo
  gather_facts: true
 
  roles:
    - install_nginx

- name: Setup nginx with SSL
  hosts: webserver
  become: yes
  become_method: sudo
  gather_facts: true
 
  roles:
    - configure_nginx_with_ssl
