---
# tasks file for install_n_configure_nginx

- name: Update repository cache and install Nginx Package.
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - nginx

- name: create index.html
  blockinfile: 
    path: /var/www/html/index.html
    block: |
        <html>
        <head>
        <title>Hello World</title>
        </head>
        <body>
        <h1>Hello World!<h1>
        </body>
        </html>


- name: Allow Nginx Full
  ufw:
    rule: allow
    name: Nginx Full
    state: enabled
 
- name: Allow Nginx Full
  ufw:
    rule: allow
    name: OpenSSH
    state: enabled
 
- name: Start nginx
  service:
    name: nginx
    state: started

- wait_for:
  port: 80 

